---
- name: Set variable base
  ansible.builtin.set_fact:
    openvpn_client_service_name: "openvpn-client@{{ openvpn_name }}"
    openvpn_client_name: "client-{{ inventory_hostname }}"
    openvpn_client_crypt_path: "{{ openvpn_name }}"

- name: Copy PKI artifacts
  ansible.builtin.copy:
    src: "{{ openvpn_temp_dist }}/{{ openvpn_client_name }}.tar.gz"
    dest: "{{ openvpn_config_path }}"
- name: Unarchive PKI artifacts
  ansible.builtin.unarchive:
    src: "{{ openvpn_config_path }}/{{ openvpn_client_name }}.tar.gz"
    dest: "{{ openvpn_config_path }}"
    extra_opts: ["--strip-components=1"]
    remote_src: yes
- name: Set client template variables
  ansible.builtin.set_fact:
    openvpn_client_ca_path: "{{ openvpn_client_crypt_path }}/ca.crt"
    openvpn_client_cert_path: "{{ openvpn_client_crypt_path }}/{{ openvpn_client_name }}.crt"
    openvpn_client_key_path: "{{ openvpn_client_crypt_path }}/{{ openvpn_client_name }}.key"
    openvpn_client_ta_key_path: "{{ openvpn_client_crypt_path }}/ta.key"
    openvpn_client_host: "{{ openvpn_host }}"
    openvpn_client_port: "{{ openvpn_conf_port }}"
- name: Openvpn client config
  ansible.builtin.template:
    src: client.conf.j2
    dest: "{{ openvpn_config_path }}.conf"
    owner: root
    #group:
    mode: 640
- name: Systemd start & enable
  ansible.builtin.systemd_service:
    name: "{{openvpn_client_service_name}}"
    state: restarted
    enabled: true
