---
- name: Validate openvpn required var are set
  ansible.builtin.assert:
    fail_msg: "[{{item}}] needs to be defined"
    success_msg: "[{{item}}] defined"
    that:
      - "{{lookup('ansible.builtin.vars', item) is defined}}"
      - "{{lookup('ansible.builtin.vars', item)|length > 0}}"
  with_items:
    - "openvpn_host"
    - "openvpn_name"

- name: Debug variables list
  ansible.builtin.debug:
    msg: 
      - "config path: {{openvpn_config_path}}"
      - "config pki path: {{openvpn_config_pki_path}}"
      - "pkgs: {{openvpn_pkgs}}"
      - "openvpn_host: {{openvpn_host}}"
      - "openvpn_name: {{openvpn_name}}"
  when: debug is defined and debug

- name: Install required packages
  ansible.builtin.package:
    name: "{{ openvpn_pkgs }}"
    state: present

- name: "Create base [{{ openvpn_name }}] config dir"
  ansible.builtin.file:
    path: "{{ openvpn_config_path  }}"
    state: directory
  become: true

- name: Set pki_master host for later ref
  ansible.builtin.set_fact:
    pki_manager: "{{ item }}"
  with_items: "{{ groups['openvpn']}}"
  when: hostvars[item]['openvpn_pki_manager']|default(false)

- name: PKI manager
  ansible.builtin.include_tasks:
    file: pki_manager.yml
  when: openvpn_pki_manager

- name: Sync pki_master temp dir to all hosts
  ansible.builtin.set_fact:
    openvpn_temp_dist: "{{hostvars[pki_manager].openvpn_temp_dist}}"

- name: Host configuration
  ansible.builtin.include_tasks:
    file: "{{item}}.yml"
  with_items:
    - "server"
    - "client"
  when: item in openvpn_role

- name: Clean up
  ansible.builtin.include_tasks:
    file: cleanup.yml
  when: openvpn_pki_manager

