---
- debug:
    msg: "{{ openvpn_config_pki_path }}"
- name: Create PKI holding directory
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    recurse: true
    mode: "0770"
    path: "{{ item }}"
  with_items:
    - "{{ openvpn_config_pki_path }}"
    - "{{ openvpn_config_pki_path }}/dist"


- name: Init client list
  set_fact:
    openvpn_clients_lst: []
    openvpn_servers_lst: []
- name: Set client list
  # TODO: Need to find a way to filter by vpn name as well
  set_fact:
    openvpn_clients_lst: "{{ openvpn_clients_lst + [item] }}"
  with_items: "{{ groups['openvpn']}}"
  when: hostvars[item]['openvpn_role'] == 'client'
- name: Set server list
  # TODO: Need to find a way to filter by vpn name as well
  set_fact:
    openvpn_servers_lst: "{{ openvpn_servers_lst + [item] }}"
  with_items: "{{ groups['openvpn']}}"
  when: hostvars[item]['openvpn_role'] == 'server'
- debug:
    msg: 
      - "Clients: {{openvpn_clients_lst}}"
      - "Server: {{openvpn_servers_lst}}"

- name: Easyrsa init-pki
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_bin_path }} init-pki"
    chdir: "{{ openvpn_config_pki_path }}"
    creates: "{{ openvpn_config_pki_path }}/pki"

- name: Easy-rsa build-ca
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_bin_path }} build-ca nopass"
    chdir: "{{ openvpn_config_pki_path }}"
    creates: "{{ openvpn_config_pki_path }}/pki/ca.crt"
  environment:
    EASYRSA_BATCH:  "yes"
    EASYRSA_DN:     "cn_only"
    EASYRSA_REQ_CN: "{{openvpn_name}}"

- name: Easyrsa gen-dh
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_bin_path }} gen-dh"
    chdir: "{{ openvpn_config_pki_path }}"
    creates: "{{ openvpn_config_pki_path }}/pki/dh.pem"

- name: Easyrsa build-server-full server nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_bin_path }} build-server-full server-{{ item }} nopass"
    chdir: "{{ openvpn_config_pki_path }}"
    creates: "{{ openvpn_config_pki_path }}/pki/issued/server-{{item}}.crt"
  environment:
    EASYRSA_BATCH: "yes"
  with_items: "{{ openvpn_servers_lst }}"

- name: Easyrsa build-client-full client nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_bin_path }} build-client-full client-{{ item }} nopass"
    chdir: "{{ openvpn_config_pki_path }}"
    creates: "{{ openvpn_config_pki_path }}/pki/issued/client-{{ item }}.crt"
  environment:
    EASYRSA_BATCH: "yes"
  with_items: "{{ openvpn_clients_lst }}"

- name: Easyrsa gen-crl
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_bin_path }} gen-crl"
    chdir: "{{ openvpn_config_pki_path }}"
    creates: "{{ openvpn_config_pki_path }}/pki/crl.pem"

- name: Openvpn --genkey --secret {{ openvpn_config_pki_path }}/pki/ta.key"
  ansible.builtin.command:
    cmd: openvpn --genkey --secret {{ openvpn_config_pki_path }}/pki/ta.key
    creates: "{{ openvpn_config_pki_path }}/pki/ta.key"

- name: Filelist init
  ansible.builtin.set_fact:
    dir_dist_list: []
    dist_filelist: []

- name: Client Generate filelist to copy (ta/ca/dh)
  ansible.builtin.set_fact:
    dist_filelist: "{{ dist_filelist + [{
      'host': item.0,
      'src': openvpn_config_pki_path+'/'+item.1,
      'dest': openvpn_config_pki_dist_path+'/'+openvpn_pki_client_prefix+item.0+'/'+(item.1 | basename )
      }] }}"
  loop: "{{openvpn_clients_lst | product(['pki/ta.key','pki/ca.crt']) | list}}"

- name: Client Generate filelist to copy (crt/key)
  ansible.builtin.set_fact:
    dist_filelist: "{{ dist_filelist + [{
      'host': item.0,
      'src': openvpn_config_pki_path+'/pki/'+item.1+'/'+openvpn_pki_client_prefix+item.0+'.'+('crt' if item.1 == \"issued\" else 'key' ),
      'dest': openvpn_config_pki_dist_path+'/'+openvpn_pki_client_prefix+item.0+'/'
      }] }}"
  loop: "{{openvpn_clients_lst | product(['issued','private']) | list}}"

- name: Server Generate filelist to copy (ta/ca/dh)
  ansible.builtin.set_fact:
    dist_filelist: "{{ dist_filelist + [{
      'host': item.0,
      'src': openvpn_config_pki_path+'/'+item.1,
      'dest': openvpn_config_pki_dist_path+'/'+openvpn_pki_server_prefix+item.0+'/'+(item.1 | basename )
      }] }}"
  loop: "{{openvpn_servers_lst | product(['pki/ta.key','pki/ca.crt', 'pki/dh.pem']) | list}}"

- name: Server Generate filelist to copy (crt/key)
  ansible.builtin.set_fact:
    dist_filelist: "{{ dist_filelist + [{
      'host': item.0,
      'src': openvpn_config_pki_path+'/pki/'+item.1+'/'+openvpn_pki_server_prefix+item.0+'.'+('crt' if item.1 == \"issued\" else 'key' ),
      'dest': openvpn_config_pki_dist_path+'/'+openvpn_pki_server_prefix+item.0+'/'
      }] }}"
  loop: "{{openvpn_servers_lst | product(['issued','private']) | list}}"

- name: Distinct dist path to creates 1/2
  ansible.builtin.set_fact:
    dir_dist_list: "{{ dir_dist_list + [ item | dirname ] }}"
  loop: "{{dist_filelist | map(attribute='dest') }}"

- name: Distinct dist path to creates 2/2
  ansible.builtin.set_fact:
    dir_dist_list: "{{ dir_dist_list | unique() }}"

- name: Create dist paths
  ansible.builtin.file:
    state: directory
    owner: root
    group: root
    recurse: true
    mode: "0770"
    path: "{{ item }}"
  loop: "{{ dir_dist_list }}"

- name: Copy the files for distribution
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.src }}"
    dest:  "{{ item.dest }}"
  with_items: "{{ dist_filelist }}"

# - name: Server dist
#   ansible.builtin.debug:
#     msg: "cp {{openvpn_config_pki_path}}/{{item.1}} {{openvpn_config_pki_dist_path}}/{{item.0}}/{{ item.1 | basename }}"
#   loop: "{{openvpn_servers_lst | product(['ta.key','pki/ca.crt', 'pki/dh.pem']) | list}}"

# - name: Server dist cert/key
#   ansible.builtin.debug:
#     msg: "cp {{openvpn_config_pki_path}}/pki/{{item.1}}/server-{{ item.0 }}.{{ 'crt' if item.1 == \"issued\" else 'key' }} {{openvpn_config_pki_dist_path}}/{{item.0}}/"
#   loop: "{{openvpn_servers_lst | product(['issued','private']) | list}}"